In [2]:
import pandas as pd
df= pd.read_csv("/mnt/c/ObesityDataSet_raw_and_data_sinthetic.csv") # path
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [3]:
# binary categories to 0/1
from sklearn.preprocessing import LabelEncoder 
from numpy import array 

def bi_category(category):
    cate=array(category)
    encoder = LabelEncoder()
    cate_encoded =  encoder.fit_transform(cate) 
    category = cate_encoded
    return cate_encoded

df.Gender = bi_category(df.Gender)
df.family_history_with_overweight = bi_category(df.family_history_with_overweight)
df.FAVC = bi_category(df.FAVC)
df.SMOKE = bi_category(df.SMOKE)
df.SCC = bi_category(df.SCC)
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,0,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight
1,0,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,1,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,1,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,0,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,1,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,0,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,1,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,0,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
# frequency categories
def freq_category(s):
    df.loc[df[s] == "no", s] = 0
    df.loc[df[s] == "Sometimes", s] = 1
    df.loc[df[s] == "Frequently", s] = 2
    df.loc[df[s] == "Always", s] = 3
freq_category('CAEC')
freq_category('CALC')
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,1,0,2.0,0,0.0,1.0,0,Public_Transportation,Normal_Weight
1,0,21.0,1.52,56.0,1,0,3.0,3.0,1,1,3.0,1,3.0,0.0,1,Public_Transportation,Normal_Weight
2,1,23.0,1.80,77.0,1,0,2.0,3.0,1,0,2.0,0,2.0,1.0,2,Public_Transportation,Normal_Weight
3,1,27.0,1.80,87.0,0,0,3.0,3.0,1,0,2.0,0,2.0,0.0,2,Walking,Overweight_Level_I
4,1,22.0,1.78,89.8,0,0,2.0,1.0,1,0,2.0,0,0.0,0.0,1,Public_Transportation,Overweight_Level_II

In [5]:
# MTRANS and label 
df.MTRANS=array(df.MTRANS)
encoder = LabelEncoder()
cate_encoded_MTRANS =  encoder.fit_transform(df.MTRANS) 
df.MTRANS = cate_encoded_MTRANS
df.loc[df["NObeyesdad"] == "Insufficient_Weight", "NObeyesdad"] = 0
df.loc[df["NObeyesdad"] == "Normal_Weight", "NObeyesdad"] = 1
df.loc[df["NObeyesdad"] == "Overweight_Level_I", "NObeyesdad"] = 2
df.loc[df["NObeyesdad"] == "Overweight_Level_II", "NObeyesdad"] = 3
df.loc[df["NObeyesdad"] == "Overweight_Level_III", "NObeyesdad"] = 4
df.loc[df["NObeyesdad"] == "Obesity_Type_I", "NObeyesdad"] = 5
df.loc[df["NObeyesdad"] == "Obesity_Type_II", "NObeyesdad"] = 6
df.loc[df["NObeyesdad"] == "Obesity_Type_II", "NObeyesdad"] = 7
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,1,0,2.0,0,0.0,1.0,0,3,1
1,0,21.0,1.52,56.0,1,0,3.0,3.0,1,1,3.0,1,3.0,0.0,1,3,1
2,1,23.0,1.80,77.0,1,0,2.0,3.0,1,0,2.0,0,2.0,1.0,2,3,1
3,1,27.0,1.80,87.0,0,0,3.0,3.0,1,0,2.0,0,2.0,0.0,2,4,2
4,1,22.0,1.78,89.8,0,0,2.0,1.0,1,0,2.0,0,0.0,0.0,1,3,3

In [7]:
# normalization
label = df.NObeyesdad
df = df.drop(columns=["NObeyesdad"])
df = (df-df.min())/(df.max()-df.min())
df["NObeyesdad"] = label
df.head(40)
df.to_csv('Processed_data.csv',index = False)